name: Main Branch Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PROD_SSH_USER }}
          SSH_KEY: ${{ secrets.PROD_SSH_KEY }}
          SSH_HOST: ${{ secrets.PROD_SSH_HOST }}

      - name: Pull latest version from GitHub
        run: ssh deploy 'cd ${{ secrets.INSTALLATION_DIRECTORY }} && git pull'

      - name: Make deployment script executable
        run: ssh deploy 'chmod +x ${{ secrets.INSTALLATION_DIRECTORY }}/deployment/github_deploy_fastapi.sh'

      - name: Run deployment script
        run: ssh deploy '${{ secrets.INSTALLATION_DIRECTORY }}/deployment/github_deploy_fastapi.sh'

      - name: Restart fastapi systemd service
        run: ssh deploy 'sudo systemctl restart fastapi'

      - name: Restart nginx
        run: ssh deploy 'sudo systemctl restart nginx'
